import {
  AUTOMATED_COVERAGE_NOTE,
  PRODUCT_NAME,
  domainOf,
  type Finding,
  type ScanReport,
} from '@attestci/core'

/**
 * Drafts an accessibility statement from real scan data.
 *
 * The thing that makes this worth building, and the thing that makes it
 * dangerous, are the same: an accessibility statement is a public document that
 * a regulator may read. Every generator in this category is one careless
 * sentence away from publishing a conformance claim on a customer's behalf.
 *
 * So three rules are enforced in the output, not left to the caller:
 *
 * 1. **It never states a conformance level.** The statement describes what was
 *    tested and what was found. "Partially conformant" is a determination and we
 *    are not in a position to make it.
 * 2. **It states its own method and its method's limits** in the body, in the
 *    section a reader reaches before the findings.
 * 3. **It is marked DRAFT** and says what a human must do before publishing it.
 *    A generated statement published unread is worse than no statement, because
 *    it is a public document asserting something nobody checked.
 *
 * The structure follows the model statement used under the EU Web Accessibility
 * Directive (Commission Implementing Decision (EU) 2018/1523), which is the
 * shape European readers and regulators expect, with the conformance section
 * deliberately left for the human to complete.
 */

export interface StatementInput {
  organisationName: string
  serviceName: string
  serviceUrl: string
  /** Where a user reports a barrier. Required — a statement without one is not one. */
  feedbackEmail: string
  feedbackUrl?: string
  /** National enforcement body, which differs by member state. */
  enforcementBody?: { name: string; url: string }
  /** Reports the statement is drawn from, oldest first. */
  reports: readonly ScanReport[]
  /** Manual testing the organisation has done, if any. */
  manualTesting?: {
    performedBy: string
    date: string
    scope: string
  }
  preparedOn?: string
}

export interface GeneratedStatement {
  markdown: string
  /** Everything a human must resolve before this can be published. */
  todos: string[]
  /** Facts the statement asserts, so they can be checked against the reports. */
  basis: {
    reportHashes: string[]
    scanDates: string[]
    layersRun: string[]
    layersNotRun: string[]
    findingCount: number
  }
}

export function generateStatement(input: StatementInput): GeneratedStatement {
  const latest = input.reports[input.reports.length - 1]
  if (!latest) throw new Error('Cannot draft a statement with no scan reports')

  const preparedOn = input.preparedOn ?? latest.scan.startedAt.slice(0, 10)
  const todos: string[] = []
  const out: string[] = []

  const ran = latest.coverage.layers.filter((l) => l.ran)
  const notRun = latest.coverage.layers.filter((l) => !l.ran)
  const byDomain = groupFindings(latest.findings)

  out.push(`# DRAFT — Accessibility statement for ${input.serviceName}`)
  out.push('')
  out.push(
    `> **This is a draft generated by ${PRODUCT_NAME} from automated scan data. ` +
      `It is not ready to publish.** Every section marked _[REVIEW]_ needs a human ` +
      `decision that no tool can make. Publishing this unread would assert things ` +
      `nobody has checked.`,
  )
  out.push('')

  /* ---------------------------------------------------------- commitment -- */
  out.push('## Commitment')
  out.push('')
  out.push(
    `${input.organisationName} is committed to making ${input.serviceName} accessible, ` +
      `in accordance with applicable accessibility requirements.`,
  )
  out.push('')
  out.push(`This statement applies to [${input.serviceUrl}](${input.serviceUrl}).`)
  out.push('')
  todos.push(
    'Confirm the scope sentence covers every part of the service you intend it to cover, ' +
      'and no more. Sub-domains, mobile apps and PDFs are separate scopes.',
  )

  /* -------------------------------------------------- conformance status -- */
  out.push('## Conformance status')
  out.push('')
  out.push('_[REVIEW] — this section requires a human determination._')
  out.push('')
  out.push(
    'The technical standard referenced by the European Accessibility Act is EN 301 549, ' +
      'which incorporates WCAG 2.1 Level AA. Conformance is normally stated as *fully ' +
      'conformant*, *partially conformant*, or *not conformant*.',
  )
  out.push('')
  out.push(
    `**${PRODUCT_NAME} cannot determine which of those applies and this draft does not ` +
      `state one.** Automated testing evaluates only a subset of the success criteria; the ` +
      `remainder require human judgement and testing with assistive technology. A ` +
      `conformance status should be stated only on the basis of an evaluation that ` +
      `included both.`,
  )
  out.push('')
  todos.push(
    'Decide and write the conformance status. This needs a manual evaluation. Do not ' +
      'state a status on the basis of automated results alone.',
  )

  /* ---------------------------------------------- non-accessible content -- */
  out.push('## Known non-accessible content')
  out.push('')
  if (latest.findings.length === 0) {
    out.push(
      'The most recent automated scan found no issues in the checks that ran. ' +
        'This is not a statement that the service has no accessibility barriers — see ' +
        '"How this statement was prepared" below for what was not tested.',
    )
    out.push('')
    todos.push(
      'Add any barriers known from manual testing, user feedback or an audit. A section ' +
        'listing nothing, on a service that has never been manually tested, will not be ' +
        'read as credible.',
    )
  } else {
    out.push('The following were identified by automated testing and are not yet resolved.')
    out.push('')
    if (byDomain.accessibility.length > 0) {
      out.push('### Accessibility')
      out.push('')
      for (const group of summarise(byDomain.accessibility)) {
        out.push(`- **${group.title}** — ${group.count} ${group.count === 1 ? 'instance' : 'instances'}${group.criteria ? ` (${group.criteria})` : ''}`)
      }
      out.push('')
      todos.push(
        'For each item above, add the remediation date you are committing to. A list of ' +
          'known barriers with no dates is a list of admissions.',
      )
    }
    if (byDomain.privacy.length > 0 || byDomain['client-impact'].length > 0) {
      out.push('')
      out.push(
        '_[REVIEW] — the scan also reported findings about data placement and client cost. ' +
          'Those are engineering concerns and do not belong in an accessibility statement. ' +
          'They are excluded from this section deliberately; delete this note before publishing._',
      )
      out.push('')
    }
  }

  if (latest.suppressed.length > 0) {
    out.push('### Accepted for now')
    out.push('')
    out.push(
      `${latest.suppressed.length} automated ${latest.suppressed.length === 1 ? 'finding was' : 'findings were'} ` +
        `reviewed and accepted, each with a recorded reason. _[REVIEW] — decide which of ` +
        `these a reader of this statement should be told about._`,
    )
    out.push('')
    todos.push('Review the suppressed findings and decide which belong in the public statement.')
  }

  /* --------------------------------------------------------- preparation -- */
  out.push('## How this statement was prepared')
  out.push('')
  out.push(`This statement was prepared on ${preparedOn}.`)
  out.push('')
  out.push('**Automated testing.**')
  out.push('')
  out.push(
    `${input.reports.length} automated ${input.reports.length === 1 ? 'scan' : 'scans'} ` +
      `were performed using ${PRODUCT_NAME} ${latest.tool.version}, most recently on ` +
      `${latest.scan.startedAt.slice(0, 10)}. Accessibility checks are performed by ` +
      `axe-core, developed and maintained by Deque Systems.`,
  )
  out.push('')
  out.push('What the automated testing covered:')
  out.push('')
  for (const layer of ran) {
    out.push(`- ${layerLabel(layer.kind)}: ${layer.rulesRun} rules over ${layer.unitsExamined} ${layer.unitLabel}`)
  }
  if (latest.target.urls.length > 0) {
    out.push('')
    out.push(`Pages evaluated: ${latest.target.urls.map((u) => `\`${u}\``).join(', ')}.`)
    todos.push(
      'Confirm the pages listed are representative of the service. Pages that were not ' +
        'scanned are not covered by any statement made here.',
    )
  }
  out.push('')

  if (notRun.length > 0) {
    out.push('What the automated testing did **not** cover:')
    out.push('')
    for (const layer of notRun) {
      out.push(`- ${layerLabel(layer.kind)} — ${layer.reason ?? 'did not run'}`)
    }
    out.push('')
  }

  out.push(`**Limits of automated testing.** ${AUTOMATED_COVERAGE_NOTE}`)
  out.push('')

  if (input.manualTesting) {
    out.push('**Manual testing.**')
    out.push('')
    out.push(
      `Manual evaluation was performed by ${input.manualTesting.performedBy} on ` +
        `${input.manualTesting.date}, covering ${input.manualTesting.scope}.`,
    )
    out.push('')
  } else {
    out.push('**Manual testing.**')
    out.push('')
    out.push(
      '_[REVIEW] — no manual evaluation is recorded. A statement based on automated testing ' +
        'alone should say so plainly, and most readers will treat it as incomplete, because ' +
        'it is. If manual testing has been done, describe who did it, when, and what it ' +
        'covered._',
    )
    out.push('')
    todos.push(
      'Arrange or record a manual evaluation. This is the single largest gap in the ' +
        'statement and the one a regulator is most likely to ask about.',
    )
  }

  /* ------------------------------------------------------------ feedback -- */
  out.push('## Feedback')
  out.push('')
  out.push(
    `If you encounter a barrier using ${input.serviceName}, please tell us at ` +
      `[${input.feedbackEmail}](mailto:${input.feedbackEmail})` +
      (input.feedbackUrl ? ` or through [our feedback form](${input.feedbackUrl})` : '') +
      '.',
  )
  out.push('')
  out.push('_[REVIEW] — state the response time you will actually meet._')
  out.push('')
  todos.push(
    'Commit to a response time you can meet, and make sure somebody is monitoring the ' +
      'address. An unmonitored feedback address is worse than none.',
  )

  /* --------------------------------------------------------- enforcement -- */
  out.push('## Enforcement procedure')
  out.push('')
  if (input.enforcementBody) {
    out.push(
      `If you are not satisfied with our response, you may contact ` +
        `[${input.enforcementBody.name}](${input.enforcementBody.url}).`,
    )
  } else {
    out.push(
      '_[REVIEW] — name the enforcement body for each member state where this service is ' +
        'offered. These differ by country and there is no single EU-wide body._',
    )
    todos.push(
      'Identify the enforcement body for every member state you serve, and name each one. ' +
        'This is jurisdiction-specific and is a question for a lawyer, not a tool.',
    )
  }
  out.push('')

  /* ------------------------------------------------------------- footer --- */
  out.push('---')
  out.push('')
  out.push(
    `_Drafted by ${PRODUCT_NAME} from ${input.reports.length} scan ` +
      `${input.reports.length === 1 ? 'report' : 'reports'}. Most recent report hash: ` +
      `\`${latest.contentHash}\`._`,
  )
  out.push('')
  out.push(
    '_This draft reports the results of automated checks and does not determine ' +
      'conformance with any standard. It is not legal advice. It must be reviewed and ' +
      'completed by a person before publication._',
  )
  out.push('')

  return {
    markdown: out.join('\n'),
    todos,
    basis: {
      reportHashes: input.reports.map((r) => r.contentHash),
      scanDates: input.reports.map((r) => r.scan.startedAt),
      layersRun: ran.map((l) => l.kind),
      layersNotRun: notRun.map((l) => l.kind),
      findingCount: latest.findings.length,
    },
  }
}

function groupFindings(findings: readonly Finding[]) {
  const out = {
    accessibility: [] as Finding[],
    privacy: [] as Finding[],
    'client-impact': [] as Finding[],
  }
  for (const finding of findings) out[domainOf(finding.kind)].push(finding)
  return out
}

interface Group {
  title: string
  count: number
  criteria: string
}

function summarise(findings: readonly Finding[]): Group[] {
  const byRule = new Map<string, Finding[]>()
  for (const finding of findings) {
    byRule.set(finding.ruleId, [...(byRule.get(finding.ruleId) ?? []), finding])
  }

  return [...byRule.values()]
    .map((group) => {
      const first = group[0]!
      const criteria = [
        ...new Set(
          first.standards
            .filter((s) => s.framework === 'wcag21')
            .map((s) => `WCAG 2.1 ${s.id}${s.level ? ` Level ${s.level}` : ''}`),
        ),
      ].join(', ')
      return { title: first.title, count: group.length, criteria }
    })
    .sort((a, b) => b.count - a.count)
}

function layerLabel(kind: string): string {
  switch (kind) {
    case 'runtime-a11y':
      return 'Rendered pages evaluated with axe-core'
    case 'static-a11y':
      return 'Source code accessibility checks'
    case 'static-privacy':
      return 'Source code data placement checks'
    case 'client-impact':
      return 'Client delivery cost checks'
    default:
      return kind
  }
}
