export { runCli } from './cli.js'
export { scanCommand, type ScanOptions } from './commands/scan.js'
export { diffCommand, type DiffOptions } from './commands/diff.js'
export { badgeCommand, type BadgeOptions } from './commands/badge.js'
export { rulesCommand, explainCommand } from './commands/rules.js'
export { initCommand } from './commands/init.js'
export { allRules, findRule } from './rules.js'
export { consoleIo, collectingIo, type CliIo } from './io.js'
export { VERSION } from './version.js'
export { readGitContext, normalizeRemote } from './git.js'
